name: basemaker
version: 0.6.2
maintainer: Galen Huntington
license: MIT

default-extensions:
- BlockArguments
- DerivingStrategies
- ScopedTypeVariables
- RecordWildCards
- PatternSynonyms

executables:
  basemaker:
    main: aceofbase.hs

dependencies:
- base
- bytestring
- containers
- transformers
- tar
- wreq
- zlib
# TODO lens is pulled in transitively, so why bother?
- microlens
- microlens-th
- SHA
- xdg-basedir
- directory
- filepath
- process
- optparse-applicative

